const HARDCODED_INFO = [
  ['name','description','location','logo','banner','cafeteria number','rider number','track url','name_ar','description_ar'],
  [
   'Rukn Al Shawarma Cafeteria','A Syrian restaurant with a Levantine flavor','120th St - Al Nakheel - Ras Al Khaimah','https://drive.google.com/file/d/1Sk2Qf2hDd0E77LLzYRLVYADuct_PlLHB/view?usp=sharing',
   'https://drive.google.com/file/d/1HGhOIVtjOYnhQC-XrwQBR_Nh697qTRG1/view?usp=sharing','971588397983','971522847006','https://wa.me/971556269187',
   'كافتيريا ركن الشاورما','مطعم سوري بنكهة الشامية'
  ]
];

const HARDCODED_ITEMS = [
// [cat_en, Name_en, desc_en, price, offer_price, cat_icon, image_url, tags, cat_ar, Name_ar, desc_ar]
['Chicken Shawerma','Sandwich (Small)','','7','','1','https://drive.google.com/thumbnail?id=14Qd1U2YUtTOov7K9qbvKHdOdxK7fDjNl&sz=w1000','','شاورما دجاج','ساندويش صغير',''],
['Chicken Shawerma','Sandwich (Large)','','12','','1','https://drive.google.com/thumbnail?id=15MrLINiryh9iGodVhWZ7QXkHHT1IC-ie&sz=w1000','','شاورما دجاج','ساندويش (كبير)',''],
['Chicken Shawerma','Samoon Saroukh Sandwich','','13','','1','https://drive.google.com/thumbnail?id=1zX8KaCNE4gVTriJkvuAsF4UYCPfHocPZ&sz=w1000','','شاورما دجاج','ساندويش صمون صاروخ',''],
['Chicken Shawerma','Shawarma Tortilla Sandwich','','13','','1','https://drive.google.com/thumbnail?id=1oMvdyLbFZjDTaK3lOP2ynkqRBwve8Hru&sz=w1000','','شاورما دجاج','ساندويش شاورما توراتيلا',''],
['Chicken Shawerma','Arab','','19','','1','https://drive.google.com/thumbnail?id=1CpytnLn_gtfweIQ-OvkrNC3iDocY5aFe&sz=w1000','popular','شاورما دجاج','عربي',''],
['Chicken Shawerma','Double Arabic','','23','22','1','https://drive.google.com/thumbnail?id=14L6WWk30aOEDxiKaSUKChOMp9prqX5CL&sz=w1000','popular','شاورما دجاج','عربي دبل',''],
['Chicken Shawerma','Arabic Mix (Meat + Chicken)','','23','22','1','https://drive.google.com/thumbnail?id=1rrzTWvVP2TDVDHkpLOBFqXV-y6TnGLVx&sz=w1000','popular','شاورما دجاج','ميكس عربي (لحم + دجاج)',''],
['Chicken Shawerma','Dish Of Shawema Cutlets','','23','22','1','https://drive.google.com/thumbnail?id=1WOBin6ijMiPfp2-abSDuhiihuljJC8ze&sz=w1000','','شاورما دجاج','صحن شاورما، دونر كوتليت (كفتة)',''],
['Chicken Shawerma','Hummus With Shawarma','','23','22','1','https://drive.google.com/thumbnail?id=1kFwkOipxLNuf5zsGIKXSejgTRVogs4PF&sz=w1000','','شاورما دجاج','حمص بالشاورما',''],
['Chicken Shawerma','Rice With Shawarma','','23','22','1','https://drive.google.com/thumbnail?id=1JID6fLKyEqPNe53dPncoI0MpkSMRE-mG&sz=w1000','','شاورما دجاج','أرز بالشاورما',''],
['Chicken Shawerma','Shawerma Fattah','','27','26','1','https://drive.google.com/thumbnail?id=1NJXHl8Y5javH01vIJ-uRCgag6NU53Paz&sz=w1000','','شاورما دجاج','فتة شاورما',''],
['Chicken Shawerma','Italian','','23','22','1','https://drive.google.com/thumbnail?id=116IElaQhMb-ii6g72doE-VblPyvdehfL&sz=w1000','','شاورما دجاج','إيطالي',''],
['Chicken Shawerma','Marina','','22','','1','https://drive.google.com/thumbnail?id=1QuXrX2-g3AKozxux1Di713IWcL4Sjkf5&sz=w1000','','شاورما دجاج','مارينا',''],
['Chicken Shawerma','Shawarma Pane','','22','','1','https://drive.google.com/thumbnail?id=1yjBeDrZ9TQXwE3sdFu1w2_up_wKMWAMw&sz=w1000','','شاورما دجاج','شاورما بانيه',''],
['Chicken Shawerma','Half A Kilo With Appetizers','','50','48','1','https://drive.google.com/thumbnail?id=1-gvV_VH3yUHv91zGLAbyJy-W-cqHwvFi&sz=w1000','','شاورما دجاج','نصف كيلو مع مقبلات',''],
['Chicken Shawerma','Kilo With Appetizers','','75','72','1','https://drive.google.com/thumbnail?id=1fo5g-pkjrECZ8n73W-kX5YXTqlrLgs9a&sz=w1000','','شاورما دجاج','1 كيلو مع مقبلات',''],
['','','','','','','','','','',''],
['Meat Shawarma Section','Small Sandwich','','8','','1','https://drive.google.com/thumbnail?id=1fB5VULqzwX5lE4TusFUAd2ou-Uy1xzoi&sz=w1000','','قسم شاورما لحم','ساندويش صغير',''],
['Meat Shawarma Section','Sandwich (Large)','','15','','1','https://drive.google.com/thumbnail?id=1llH99R1q0dBBTMihpRmax9LJLHK27yW3&sz=w1000','','قسم شاورما لحم','ساندويش (كبير)',''],
['Meat Shawarma Section','Samoon Saroukh Sandwich','','16','','1','https://drive.google.com/thumbnail?id=1COMrVFcPwbgau1AJrPB15KVH587oRGiI&sz=w1000','','قسم شاورما لحم','ساندويش صمون صاروخ',''],
['Meat Shawarma Section','Shawarma Tortilla Sandwich','','16','','1','https://drive.google.com/thumbnail?id=1RumDr1G6_uGJvgSNNDS0HwlIOjqTao3A&sz=w1000','','قسم شاورما لحم','ساندويش شاورما تورتيلا',''],
['Meat Shawarma Section','Arab','','22','','1','https://drive.google.com/thumbnail?id=1wpZFtzJ2Pbb2vergjtLVkQyXubQ4jB2P&sz=w1000','popular','قسم شاورما لحم','عربي',''],
['Meat Shawarma Section','Double Arabic','','26','25','1','https://drive.google.com/thumbnail?id=1yG3F6v0mU-gfxFzx2K-rAVe2CVSNuFiL&sz=w1000','popular','قسم شاورما لحم','عربي دبل',''],
['Meat Shawarma Section','Shawarma Slices Plate','','29','28','1','https://drive.google.com/thumbnail?id=1aS2fk3qKkx0lV27YcyX-Q5cJXvOfiPsG&sz=w1000','','قسم شاورما لحم','صحن شرحات شاورما',''],
['Meat Shawarma Section','Hummus With Shawarma','','27','','1','https://drive.google.com/thumbnail?id=1HknL_VJEvvu5LCRDP91dJ3qP3yDZqUDE&sz=w1000','','قسم شاورما لحم','حمص بالشاورما',''],
['Meat Shawarma Section','Rice With Shawarma','','27','26','1','https://drive.google.com/thumbnail?id=10xHyF4Cx7m9PU_4yjvZ06r7v9ODiMYPn&sz=w1000','','قسم شاورما لحم','أرز بالشاورما',''],
['Meat Shawarma Section','Shawerma Fattah','','32','31','1','https://drive.google.com/thumbnail?id=1DqfN_h5trCtaPaq7uqJH1B4IbOM1YgZU&sz=w1000','','قسم شاورما لحم','فتة شاورما',''],
['Meat Shawarma Section','Marina','','27','26','1','https://drive.google.com/thumbnail?id=1Ddg7qMwraC5Wog9FUOyOyTlTkzwefeUD&sz=w1000','','قسم شاورما لحم','مارينا',''],
['Meat Shawarma Section','Half A Kilo With Appetizers','','55','53','1','https://drive.google.com/thumbnail?id=1qUzv-VXr7mitkIxY6aD2hh34wUMnZOQu&sz=w1000','','قسم شاورما لحم','نصف كيلو مع مقبلات',''],
['Meat Shawarma Section','1 Kilo With Appetizers,','','90','87','1','https://drive.google.com/thumbnail?id=1tFyzN3rJHz84q7owexp5Jy4p5JGdiM7K&sz=w1000','','قسم شاورما لحم','1 كيلو مع مقبلات',''],
['','','','','','','','','','',''],
['Broasted Section','Full Broasted Meal 8 Pieces','','45','43','1','https://drive.google.com/thumbnail?id=1ilpMy1WspTnibkL3ngVgdznNiecgkp0K&sz=w1000','','قسم البروستد','وجبة بروستد كاملة 8 قطع',''],
['Broasted Section','Full Broasted Meal 8 Pieces','','25','24','1','https://drive.google.com/thumbnail?id=16TUkQ9icnqbz_By4wB_Zzs_RRuvnry-i&sz=w1000','','قسم البروستد','وجبة بروستد كاملة 8 قطع',''],
['','','','','','','','','','',''],
['Chicken Machine Section','Whole Chicken Machine With Appetizers','','40','39','1','https://drive.google.com/thumbnail?id=1hYUOK2ItowsoDTuNZhG33DDhSKtF5J7j&sz=w1000','','قسم دجاج ماكينة','فروج ماكينة كامل مع المقبلات',''],
['Chicken Machine Section','Half Chicken With Appetizers','','22','22','1','https://drive.google.com/thumbnail?id=1r6ADq_LCGY4bdN5JiQOm0Jvp-kNq9QQk&sz=w1000','','قسم دجاج ماكينة','نصف فروج ماكينة كامل مع المقبلات',''],
['','','','','','','','','','',''],
['Sandwich','Crispy Sandwich','','16','','1','https://drive.google.com/thumbnail?id=14cjfcsQiTA36A5mZFt0jwd7bycJtczt2&sz=w1000','','ساندويش غربي ','ساندويش كريسبي',''],
['Sandwich','Scallop Sandwich','','16','','1','https://drive.google.com/thumbnail?id=1JVQetBnIGi1LwlXCbX2oDZyKdXycnwMr&sz=w1000','','ساندويش غربي ','ساندويش سكالوب',''],
['Sandwich','Zinger Sandwich','','16','','1','https://drive.google.com/thumbnail?id=13gUm9rUw31dZdTPe_NiAfiGinRube_QX&sz=w1000','','ساندويش غربي ','ساندويش زنجر',''],
['Sandwich','Fajita Sandwich','','16','','1','https://drive.google.com/thumbnail?id=1AymocNiy2pNv7zHXygh2CWdKyEBvsbaB&sz=w1000','','ساندويش غربي ','ساندويش فاهيتا',''],
['Sandwich','Francesco Sandwich','','16','','1','https://drive.google.com/thumbnail?id=137LB_TgVE0bea4h76qPoZvlH5iTFsAGR&sz=w1000','','ساندويش غربي ','ساندويش فرانشيسكو',''],
['Sandwich','Mexicano Sandwich','','16','','1','https://drive.google.com/thumbnail?id=17rdGhEU8eNnJCEakuztuCpkXK9gHEfK8&sz=w1000','','ساندويش غربي ','ساندويش مكسيكانو',''],
['Sandwich','Shish Sandwich','','15','','1','https://drive.google.com/thumbnail?id=1BS1x0jS2pQ5syGLvwSSohn3SvMFA5QVg&sz=w1000','','ساندويش غربي ','ساندويش شيش',''],
['Sandwich','Shish Samoon Sandwich','','17','','1','https://drive.google.com/thumbnail?id=1w-piZQnAElNu2Wj38nKa2E40opVNnKPK&sz=w1000','','ساندويش غربي ','ساندويش صمون شيش',''],
['Sandwich','Chicken Burger','','14','','1','https://drive.google.com/thumbnail?id=11E5qrn1FzcT8hA-ZE2Tlx_R80IDc1ILi&sz=w1000','','ساندويش غربي ','برجر دجاج',''],
['Sandwich','Beef Burger','','16','','1','https://drive.google.com/thumbnail?id=1I_dYq5q_sMj9L4J2iwJWkO4Nw6s6ffwm&sz=w1000','','ساندويش غربي ','برجر لحم',''],
['','','','','','','','','','',''],
['Meals','Crispy Meal and Pepsi','','23','22','1','https://drive.google.com/thumbnail?id=1pRsorpSiKVaS7wRnxOLo8RM6u0jCjVLM&sz=w1000','','وجبات غربي','وجبة كريسبي + بيبسي',''],
['Meals','Crispy Meal 4 Pieces','','26','25','1','https://drive.google.com/thumbnail?id=1ZNYAkjNUTL6JlXymjzmDplTSjLEo9xkN&sz=w1000','','وجبات غربي','وجبة كريسبي 4 قطع',''],
['Meals','Crispy Meal 8 Pieces','','43','42','1','https://drive.google.com/thumbnail?id=1wCKJ_Toh3b0pG3kql0omf_gQ5RGvLDJh&sz=w1000','','وجبات غربي','وجبة كريسبي 8 قطع',''],
['Meals','Scallop Meal + Pepsi','','23','','1','https://drive.google.com/thumbnail?id=1bTGNDoRfnYhpgmansGM3WXZnXDL4Ps1N&sz=w1000','','وجبات غربي','وجبة سكالوب + بيبسي',''],
['Meals','Scallop Meal 4 Pieces','','26','','1','https://drive.google.com/thumbnail?id=12EqnMAKE9diEhpsDc21H9Ds1EbwgnU4u&sz=w1000','','وجبات غربي','وجبة سكالوب 4 قطع',''],
['Meals','Zinger Meal + Pepsi','','23','','1','https://drive.google.com/thumbnail?id=113kxnXGSFZg6Vy4zQu196pnlJ6DjtuSf&sz=w1000','','وجبات غربي','وجبة زنجر + بيبسي',''],
['Meals','Fajita Meal + Pepsi','','23','','1','https://drive.google.com/thumbnail?id=1wMqVLOGXXqdvAwMiqC-YJjidH3B_ePZW&sz=w1000','','وجبات غربي','وجبة فاهيتا + بيبسي',''],
['Meals','Francesco Meal + Pepsi','','23','','1','https://drive.google.com/thumbnail?id=1UHXp6KWlptRNADw19D3PwLcb1ngCZMy4&sz=w1000','','وجبات غربي','وجبة فرانشيسكو + بيبسي',''],
['Meals','Mexicano Meal + Pepsi','','2','','1','https://drive.google.com/thumbnail?id=11GMed4wvmiFqdlBWJUOFA9pYkaIJcL0j&sz=w1000','','وجبات غربي','وجبة مكسيكانو + بيبسي',''],
['Meals','Arabic Shish Meal','','318','','1','https://drive.google.com/thumbnail?id=1_D12RrtInQXoitc7Zwm7jsbwPXDloEIm&sz=w1000','popular','وجبات غربي','وجبة شيش عربي',''],
['Meals','Shish Meal With Rice','','23','','1','https://drive.google.com/thumbnail?id=1OHe_3MevuZIXh5RF4Y7S1__8MKjypVKh&sz=w1000','','وجبات غربي','وجبة شيش مع أرز',''],
['Meals','Half Kg Shish With Appetizers','','37','35','1','https://drive.google.com/thumbnail?id=12QJDxe_75M4DaVpbRvAnHqs5MDvkdUDj&sz=w1000','','وجبات غربي','نصف كيلو شيش مع مقبلات',''],
['Meals','1 Kilo Shish With Appetizers','','62','59','1','https://drive.google.com/thumbnail?id=1DRWTIZMYE0K_MBcchrkSe0EXuaSr76GH&sz=w1000','','وجبات غربي','كيلو شيش مع مقبلات',''],
['','','','','','','','','','',''],
['Family Offers','2 Machine Chicken With 12 Pieces Of Broasted','','120','114','1','https://drive.google.com/thumbnail?id=1KXE9DbyOB3FRp-7UbFSm_Fd2ajrURLc-&sz=w1000','','عروض عائلية','2فروج ماكينه مع 12 قطعة بروستيد',''],
['Family Offers','Beef Burger With Chicken Burger With Mix Shawarma','','39','37','1','https://drive.google.com/thumbnail?id=1nGCa7HmjRF7kkykPimzdQnkUk3xTV92N&sz=w1000','','عروض عائلية','برغر لحم مع برغر دجاج مع مكس شاورما',''],
['Family Offers','Western Box With 12 Pieces Of Broaste','','99','94','1','https://drive.google.com/thumbnail?id=17LUnp-HEVVyZf1qrXX2Qw59ld0rxckY4&sz=w1000','','عروض عائلية','بوكس غربي مع 12 قطعة بروستيد',''],
['Family Offers','Happiness Box With 2 Arabic Chicken','','80','76','1','https://drive.google.com/thumbnail?id=1JcbOZG66_7EOi5lautQfaWh8w6biJtgl&sz=w1000','popular','عروض عائلية','بوكسالسعادة مع 2 عربي دجاج',''],
['Family Offers','Ruken Shawarma Box With Family Meat Shawarma Box','','99','94','1','https://drive.google.com/thumbnail?id=1iDIWRQ9yVGzKBDxl6tTODtRlJ-uA_1kI&sz=w1000','','عروض عائلية','بوكس ركن الشاوما مع بوكس شاورما لحم عائلي',''],
['Family Offers','Family Shawarma Box With 12 Crispy Pieces','','99','94','1','https://drive.google.com/thumbnail?id=16FUSHlR-xbHixb8OyTDyIp9luACaKhbA&sz=w1000','','عروض عائلية','بوكس شاورما عائلي مع 12 قطعه بروستيد',''],
['Family Offers','Chicken Machine With 2 Arabic Chicken Shawarma','','70','67','1','https://drive.google.com/thumbnail?id=1FwW8j_1FP6xk7Jhv-B8Z_ggqJmbkvBHH&sz=w1000','popular','عروض عائلية','فروج ماكينة مع 2 شاورما عربي دجاج',''],
['','','','','','','','','','',''],
['Person Offers','2 Pieces Of Zinger With Rice','','15','','1','https://drive.google.com/thumbnail?id=1pHU4W_xvgHMTC10NNjkstz9Z7ffcYorg&sz=w1000','','عروض فردية','2 قطعة زنجر مع أرز',''],
['Person Offers','Meat Slices With Rice','','18','','1','https://drive.google.com/thumbnail?id=1bavuK90AdONUWx1PER8pLy6sczj5T50X&sz=w1000','','عروض فردية','شرحات اللحم مع أرز',''],
['Person Offers','2 Pieces Crispy With Rice','','15','','1','https://drive.google.com/thumbnail?id=17u1mJh1UrmjthoHeyhhtWe7WUKzIkFYa&sz=w1000','','عروض فردية','2 قطعة كريسبي مع أرز',''],
['Person Offers','Chicken Shawarma Slices With Rice','','15','','1','https://drive.google.com/thumbnail?id=1jrCpXshQYkaJ3BKQ_GgCNgzF-43LtdEk&sz=w1000','','عروض فردية','شرحات شاورما دجاج مع أرز',''],
['','','','','','','','','','',''],
['Box Section','Box Roken Al Shawarma','','65','62','1','https://drive.google.com/thumbnail?id=1-LtK4gQt4rhjLt5DW81XlrocGmyvsni_&sz=w1000','','قسم البوكس','بوكس ركن الشاوما',''],
['Box Section','Happiness Box','','62','60','1','https://drive.google.com/thumbnail?id=1jrq6ZkSbrhdbp73P_IQCMpBNE6dk--e_&sz=w1000','','قسم البوكس','بوكس السعادة',''],
['Box Section','Western Box','','60','58','1','https://drive.google.com/thumbnail?id=1U7PleYq0_7_0YKTbNqFGYo-zFt5WaKX0&sz=w1000','','قسم البوكس','بوكس غربي',''],
['Box Section','Family Box Chicken Shawarma','','44','42','1','https://drive.google.com/thumbnail?id=1u8V5oUMtuBYSwUI5W5pdx8suNukf8a67&sz=w1000','','قسم البوكس','بوكس شاورما دجاج عائلي',''],
['Box Section','Family Box Meat Shawarma','','59','57','1','https://drive.google.com/thumbnail?id=1oWfEDD3xFFT-kERaRZEtHd159T-k3nYl&sz=w1000','','قسم البوكس','بوكس شاورما لحم عائلي',''],
['','','','','','','','','','',''],
['Potato Section','Potato Sandwich (Small)','','4','','1','https://drive.google.com/thumbnail?id=19MSUiC7HXkSgCSdBYlhF4Qnpm-zYtR3l&sz=w1000','','قسم البطاطا','سندويش بطاطا (صغير)',''],
['Potato Section','Potato Sandwich (Large)','','7','','1','https://drive.google.com/thumbnail?id=19MSUiC7HXkSgCSdBYlhF4Qnpm-zYtR3l&sz=w1000','','قسم البطاطا','سندويش بطاطا (كبير)',''],
['Potato Section','Samoon Potato Sandwich','','8','','1','https://drive.google.com/thumbnail?id=1BoV2Q5kZoWSFcDJYVnpCTsNSstqMb83J&sz=w1000','','قسم البطاطا','سندويش بطاطا صمون',''],
['Potato Section','Potato Plate (Small)','','8','','1','https://drive.google.com/thumbnail?id=1W-TKPFYzntPdg05CbVZx_i_dcp--HlLu&sz=w1000','','قسم البطاطا','صحن بطاطا (صغير)',''],
['Potato Section','Potato Plate (Large)','','13','','1','https://drive.google.com/thumbnail?id=1KWomlQ9uSCxbiVLDedNMb1qDBOM8zweS&sz=w1000','','قسم البطاطا','صحن بطاطا (كبير)',''],
['Potato Section','Potato Dish With Cheese','','10','','1','https://drive.google.com/thumbnail?id=1urxnDY10JehUg-yqyab-VR2P4NBuLc-Z&sz=w1000','','قسم البطاطا','صحن بطاطا بالجبن',''],
['','','','','','','','','','',''],
['Apetizers','Kibbeh Plate','','15','','','https://drive.google.com/thumbnail?id=1ZdClmlbWtfECpdCUmLPtssSkE6l1gULb&sz=w1000','','مقبلات','صحن كبة عدد 6 حبة',''],
['Apetizers','Kibbeh With A Grain','','3','','','https://drive.google.com/thumbnail?id=1pFAMxxSSM53WaFuVIU1KUlk48XwDr7Ip&sz=w1000','','مقبلات','كبة بالحبة',''],
['Apetizers','Arabic Salad Plate','','10','','1','https://drive.google.com/thumbnail?id=1RqBvet-FwJquRy72WWNHF4HKdkvtZ3iq&sz=w1000','popular','مقبلات','صحن سلطة عربي',''],
['Apetizers','Fattoush Plate','','12','','','https://drive.google.com/thumbnail?id=19rlfgqZuIvEtvKkK8L-S9B65zE28Qp8x&sz=w1000','','مقبلات','صحن فتوش',''],
['Apetizers','Hummus Plate','','10','','','https://drive.google.com/thumbnail?id=1sc7Nw_prW2UwkUm5NKHr5qfPfw7oh0TY&sz=w1000','','مقبلات','صحن حمص',''],
['','','','','','','','','','',''],
['Drinks','Soda','','3','','','https://drive.google.com/thumbnail?id=16DvZajX5nhB_onDEC27ab4nIbtewCpGQ&sz=w1000','','مشروبات','مشروب غازي',''],
['Drinks','Laban Up','','2','','','https://drive.google.com/thumbnail?id=1dvRtSEmog7dnOb-sJXibvXV5MHguF5_d&sz=w1000','','مشروبات','لبن أب',''],
['Drinks','Mineral Water','','1','','','https://drive.google.com/thumbnail?id=1SIRSSnjMyXsHmytdSE8sDIfniqRr3JEQ&sz=w1000','','مشروبات','مياه معدنية','']
];
